name: Develop CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: .\main
    - name: NerdBank.GitVersioning
      uses: dotnet/nbgv@v0.3.1
      id: nbgv
      with:
        path: .\main
    - name: Build
      run: >
        dotnet build -c Release
        -p:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }}
        -p:AssemblyFileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }}
        -p:AssemblyInformationalVersion=${{ steps.nbgv.outputs.AssemblyInformationalVersion }}
        --no-restore
      working-directory: .\main
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal .\test\ReCode.Cocoon.Proxy.Tests
      working-directory: .\main
    - name: BuildNet45
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\main\Cocoon.sln -m /p:Configuration=Release
    - name: ConsoleRunXUnitLegacyTests
      run: |
        ~/.nuget/packages/xunit.runner.console/2.4.1/tools/net472/xunit.console.exe $Env:GITHUB_WORKSPACE\main\test\ReCode.Cocoon.Legacy.Tests\bin\Release\net45\ReCode.Cocoon.Legacy.Tests.dll